"""
Scenario Injection Models Reference
This file contains the original Pydantic model definitions for scenario injection.
Generated by scripts/extract_injection_schema.py
Updated to match nested structure.
"""

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class ScenarioActInject(BaseModel):
    """시나리오 주입용 Act 정보"""

    id: str = Field(..., description="액트 식별자 (예: act-1)")
    name: str = Field(..., description="액트 이름")
    region_name: str
    region_description: str = ""
    description: Optional[str] = None
    goal: str
    exit_criteria: str
    sequences: List[str] = Field(
        default_factory=list, description="소속 시퀀스 ID 리스트"
    )


class ScenarioInjectNPC(BaseModel):
    """주입용 NPC 정보"""

    scenario_npc_id: str
    master_id: Optional[str] = None
    name: str
    description: str = ""
    tags: List[str] = []
    state: Dict[str, Any] = {}


class ScenarioInjectItem(BaseModel):
    """주입용 아이템 정보"""

    item_id: str
    master_id: Optional[str] = None
    name: str
    description: str = ""
    item_type: str = "misc"
    meta: Dict[str, Any] = {}


class ScenarioInjectEnemy(BaseModel):
    """주입용 적 정보"""

    scenario_enemy_id: str
    master_id: Optional[str] = None
    name: str
    description: str = ""
    tags: List[str] = []
    state: Dict[str, Any] = {}
    dropped_items: List[str] = []


class ScenarioInjectRelation(BaseModel):
    """주입용 관계 정보"""

    from_id: str
    to_id: str
    relation_type: str = "neutral"
    affinity: int = 50
    meta: Dict[str, Any] = {}


class ScenarioSequenceInject(BaseModel):
    """시나리오 주입용 Sequence 정보"""

    id: str = Field(..., description="시퀀스 식별자 (예: seq-1)")
    name: str = Field(..., description="시퀀스 이름")
    sequence_type: str = "Exploration"
    location_name: str
    location_master_id: Optional[str] = None
    location_theme: str = ""
    location_description: str = ""
    danger_min: int = 1
    danger_max: int = 10
    description: str
    goal: str
    exit_triggers: List[str] = Field(default_factory=list, description="탈출/전환 조건")
    npcs: List[str] = Field(default_factory=list)
    enemies: List[str] = Field(default_factory=list)
    items: List[str] = Field(default_factory=list)


class ScenarioInjectRequest(BaseModel):
    """최종 시나리오 주입 규격"""

    scenario_id: Optional[str] = None
    title: str
    summary: str = ""
    description: Optional[str] = None
    difficulty: str = "normal"
    genre: str = "fantasy"
    tags: List[str] = []
    total_acts: int = 1
    acts: List[ScenarioActInject] = []
    sequences: List[ScenarioSequenceInject] = []
    relations: List[ScenarioInjectRelation] = []
